openapi: 3.0.0
info:
  title: Parking Control Spot
  description: |
    This API is an example for API REST where is possible control a parkings spots
  contact:
    name: Renan
    url: https://linkedin.com/in/renanrodolfo
    email: renaner123@gmail.com  
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string  
    ParkingSpotModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        parkingSpotNumber:
          type: string
        registrationDate:
          type: string
        responsibleName:
          type: string   
        apartment:
          type: string   
        block:
          type: string 
        CarModel:
          type: object
    CarModel:
      type: object
      properties:
        id:
          type: integer
          format: int32
        licensePlateCar:
          type: string        
        brandCar:
          type: string   
        modelCar:
          type: object   
        colorCar:
          type: string   
        parkingSpot:
          type: string

  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'

paths:
  /parking-spot:
    get:
      description: Returns all Parking Spot
      summary: Return all Parking Spot
      operationId: findAll
      responses:
        '200':
          description: OK
          content:
            'application/json' : 
              schema:
                properties:
                  items:
                    $ref: '#/components/schemas/ParkingSpotModel'
                  carModel:
                    type: object
                    additionalProperties: 
                    $ref: '#/components/schemas/CarModel'  
  
        '500':
          description: Internal error
          content:
            string : 
              schema:
                $ref: '#/components/schemas/GeneralError'
